### ISSUE TITLE
As a player, I want to have a character that can move around

### ISSUE THREAD

**Issue by AngelOnFira** [AngelOnFira/adventure-jam-2022#1]
https://www.youtube.com/watch?v=mAbG8Oi-SvQ

**Comment by Entropy675** [comment]
Added movement and sprinting via WASD. Also added shift key for sprint, considering changing the sprint to a dash in the future? Depends on how combat will evolve in this game, if we go with a more puzzle focus then the sprint is probably good enough as is right now.
